#!/sbin/openrc-run
# Copyright 1999-2023 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2

description="NginX Unit"
description_save="Save configuration"
description_reload="(Re)load configuration"
command="/usr/sbin/unitd"
command_args="${UNITD_OPTIONS}"
pidfile="/run/nginx-unit.pid"

start_pre() {
    checkpath -d /var/lib/nginx-unit -o root:root 0770
}

depend() {
    use logger netmount
}
